
apiVersion: v1
kind: Pod

metadata:
  name: insta-pod
  labels:
    env: production 
    app: instagram 

spec:
  containers:
    - name: insta-pod-cont
      image: devopshubg333/batch16d:fb_httpd
      ports:
        - containerPort: 80
    
