apiVersion: apps/v1
kind: Deployment
metadata:
  name: kindex
  labels:
    app: kia
    env: orun
spec:
  replicas: {{ .Values.deployment.replicacount}}
  selector:
    matchLabels:
      app: kia
      env: orun
  template:
    metadata:
      name: kindex
      labels:
        app: kia
        env: orun
    spec:
      containers:
        - name: kindex-test
          image: devopshub12/mcvinay:{{ .Values.deployment.imageversion}}
          ports:
            - containerPort: 80


