apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80 #nginx default port
   
    livenessProbe:
      httpGet:
        path: /
        port: 8082
      initialDelaySeconds: 5  #waits 5sec for the nginx to start
      periodSeconds: 10
      failureThreshold: 3


      ## kubectl exec -it liveness-pod -- curl localhost:80
